# -*- coding: utf-8 -*-
"""ASBK92

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yNccJg77iuc0sFbVHE3-TPFsHOhfnS1K

# Required Libraries
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from imblearn.over_sampling import SMOTE
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from xgboost import XGBClassifier
from sklearn.metrics import (
    accuracy_score,
    classification_report,
    confusion_matrix,
    roc_auc_score
)
import shap
import lime.lime_tabular
from lime.lime_tabular import LimeTabularExplainer

# Load Dataset
df = pd.read_csv("Cloud_Anomaly_Dataset.csv")

# Display first five rows
df.head()

# Dataset Information
df.info()

# Descriptive Statistics
df.describe()

"""# EDA"""

# CPU Usage by Anomaly Status
plt.figure(figsize=(8,6))

sns.boxplot(
    x='Anomaly status',
    y='cpu_usage',
    data=df,
    palette='Set2'
)

plt.title("CPU Usage by Anomaly Status", fontsize=16)
plt.xlabel("Anomaly Status")
plt.ylabel("CPU Usage")

plt.show()

# Count Plot of Task Types
plt.figure(figsize=(8,6))

sns.countplot(
    data=df,
    x='task_type',
    palette='Paired'
)

plt.title("Distribution of Task Types", fontsize=16)
plt.xlabel("Task Type")
plt.ylabel("Count")

plt.show()

# CPU Usage vs Memory Usage
plt.figure(figsize=(9,6))

sns.scatterplot(
    data=df,
    x='cpu_usage',
    y='memory_usage',
    hue='Anomaly status',
    palette='viridis',
    alpha=0.7
)

plt.title("CPU Usage vs Memory Usage", fontsize=16)
plt.xlabel("CPU Usage")
plt.ylabel("Memory Usage")

plt.show()

# Network Traffic by Task Priority
plt.figure(figsize=(8,6))

sns.violinplot(
    data=df,
    x='task_priority',
    y='network_traffic',
    palette='Spectral'
)

plt.title("Network Traffic across Task Priorities", fontsize=16)
plt.xlabel("Task Priority")
plt.ylabel("Network Traffic")

plt.show()

"""# Data Preprocessing"""

# Check missing values
print(df.isnull().sum())

# Remove rows with missing values
df = df.dropna()

# Check duplicate rows
print("Duplicate Rows:", df.duplicated().sum())

# Feature Engineering
# Convert timestamp to datetime
df['timestamp'] = pd.to_datetime(df['timestamp'], dayfirst=True)

# Create new features
df['Day'] = df['timestamp'].dt.day
df['Month'] = df['timestamp'].dt.month
df['Hour'] = df['timestamp'].dt.hour

# Drop original timestamp column
df.drop('timestamp', axis=1, inplace=True)

# Remove VM ID
df.drop('vm_id', axis=1, inplace=True)

# Feature Encoding
# Initialize encoder
encoder = LabelEncoder()

# Encode categorical columns
categorical_columns = [
    'task_type',
    'task_priority',
    'task_status'
]

for column in categorical_columns:
    df[column] = encoder.fit_transform(df[column])

# Feature Scaling
# Features to scale
numerical_features = [
    'cpu_usage',
    'memory_usage',
    'network_traffic',
    'power_consumption',
    'num_executed_instructions',
    'execution_time',
    'energy_efficiency',
    'Day',
    'Month',
    'Hour'
]

# Initialize scaler
scaler = StandardScaler()

# Apply scaling
df[numerical_features] = scaler.fit_transform(df[numerical_features])

"""# Machine Learning"""

# Features and Target
X = df.drop('Anomaly status', axis=1)
y = df['Anomaly status']

# Split dataset
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

print("Training Samples :", X_train.shape)
print("Testing Samples  :", X_test.shape)

# Initialize SMOTE
smote = SMOTE(random_state=42)

# Apply SMOTE only on the training data
X_train_resampled, y_train_resampled = smote.fit_resample(X_train, y_train)

"""## Decision Tree Model"""

dt = DecisionTreeClassifier(random_state=42)

dt.fit(X_train_resampled, y_train_resampled)

y_pred_dt = dt.predict(X_test)
y_prob_dt = dt.predict_proba(X_test)[:,1]

# Accuracy
accuracy = accuracy_score(y_test, y_pred_dt) * 100
print(f"Decision Tree Accuracy : {accuracy:.2f}%")

# Classification Report
print("\nClassification Report")
print(classification_report(y_test, y_pred_dt))

# ROC AUC
auc = roc_auc_score(y_test, y_prob_dt)
print(f"ROC-AUC Score : {auc:.4f}")

# Confusion Matrix
cm = confusion_matrix(y_test, y_pred_dt)

plt.figure(figsize=(6,5))
sns.heatmap(cm,
            annot=True,
            fmt='d',
            cmap='Blues')

plt.title("Decision Tree Confusion Matrix")
plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.show()

"""## Random Forest Model"""

rf = RandomForestClassifier(
    n_estimators=100,
    random_state=42
)

rf.fit(X_train_resampled, y_train_resampled)

y_pred_rf = rf.predict(X_test)
y_prob_rf = rf.predict_proba(X_test)[:,1]

accuracy = accuracy_score(y_test, y_pred_rf) * 100
print(f"Random Forest Accuracy : {accuracy:.2f}%")

print("\nClassification Report")
print(classification_report(y_test, y_pred_rf))

auc = roc_auc_score(y_test, y_prob_rf)
print(f"ROC-AUC Score : {auc:.4f}")

cm = confusion_matrix(y_test, y_pred_rf)

plt.figure(figsize=(6,5))
sns.heatmap(cm,
            annot=True,
            fmt='d',
            cmap='Greens')

plt.title("Random Forest Confusion Matrix")
plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.show()

"""## Gradient Boosting Model"""

gb = GradientBoostingClassifier(random_state=42)

gb.fit(X_train_resampled, y_train_resampled)

y_pred_gb = gb.predict(X_test)
y_prob_gb = gb.predict_proba(X_test)[:,1]

accuracy = accuracy_score(y_test, y_pred_gb) * 100
print(f"Gradient Boosting Accuracy : {accuracy:.2f}%")

print("\nClassification Report")
print(classification_report(y_test, y_pred_gb))

auc = roc_auc_score(y_test, y_prob_gb)
print(f"ROC-AUC Score : {auc:.4f}")

cm = confusion_matrix(y_test, y_pred_gb)

plt.figure(figsize=(6,5))
sns.heatmap(cm,
            annot=True,
           fmt='d',
            cmap='Oranges')

plt.title("Gradient Boosting Confusion Matrix")
plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.show()

"""## XGBoost Model"""

xgb = XGBClassifier(
    random_state=42,
    eval_metric='logloss'
)

xgb.fit(X_train_resampled, y_train_resampled)

y_pred_xgb = xgb.predict(X_test)
y_prob_xgb = xgb.predict_proba(X_test)[:,1]

accuracy = accuracy_score(y_test, y_pred_xgb) * 100
print(f"XGBoost Accuracy : {accuracy:.2f}%")

print("\nClassification Report")
print(classification_report(y_test, y_pred_xgb))

auc = roc_auc_score(y_test, y_prob_xgb)
print(f"ROC-AUC Score : {auc:.4f}")

cm = confusion_matrix(y_test, y_pred_xgb)

plt.figure(figsize=(6,5))
sns.heatmap(cm,
            annot=True,
            fmt='d',
            cmap='Purples')

plt.title("XGBoost Confusion Matrix")
plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.show()

# Store results
results = pd.DataFrame({
    "Model": ["Decision Tree", "Random Forest", "Gradient Boosting", "XGBoost"],
    "Accuracy (%)": [
        accuracy_score(y_test, pred) * 100
        for pred in [y_pred_dt, y_pred_rf, y_pred_gb, y_pred_xgb]
    ],
    "ROC-AUC": [
        roc_auc_score(y_test, prob)
        for prob in [y_prob_dt, y_prob_rf, y_prob_gb, y_prob_xgb]
    ]
})

print(results.sort_values("Accuracy (%)", ascending=False))

plt.figure(figsize=(8,5))

sns.barplot(
    data=results,
    x="Model",
    y="Accuracy (%)",
    palette=["#3498db",
             "#2ecc71",
             "#f39c12",
             "#9b59b6"]
)

plt.title("Model Accuracy Comparison")
plt.xlabel("Machine Learning Model")
plt.ylabel("Accuracy (%)")

for i, value in enumerate(results["Accuracy (%)"]):
    plt.text(i, value + 0.2, f"{value:.2f}%", ha="center")

plt.show()

"""# Explainable AI

## SHAP
"""

# Create SHAP explainer
explainer = shap.TreeExplainer(xgb)

# Calculate SHAP values
shap_values = explainer.shap_values(X_test)

plt.figure(figsize=(10,6))

shap.summary_plot(
    shap_values,
    X_test,
    plot_type="dot",
    show=False
)

plt.title("SHAP Summary Plot")
plt.tight_layout()
plt.show()

plt.figure(figsize=(10,6))

shap.summary_plot(
    shap_values,
    X_test,
    plot_type="bar",
    show=False
)

plt.title("SHAP Feature Importance")
plt.tight_layout()
plt.show()

# Explain the first test instance
shap.plots.waterfall(
    shap.Explanation(
        values=shap_values[0],
        base_values=explainer.expected_value,
        data=X_test.iloc[0],
        feature_names=X_test.columns
    )
)

shap.initjs()

shap.force_plot(
    explainer.expected_value,
    shap_values[0],
    X_test.iloc[0]
)

"""## LIME"""

# Create LIME explainer
lime_explainer = LimeTabularExplainer(
    training_data=X_train_resampled.values,
    feature_names=X_train_resampled.columns,
    class_names=["Normal", "Anomaly"],
    mode="classification"
)

# Select one instance
instance = X_test.iloc[0]

# Generate explanation
lime_exp = lime_explainer.explain_instance(
    instance.values,
    xgb.predict_proba,
    num_features=10
)

lime_exp.show_in_notebook(show_table=True)

fig = lime_exp.as_pyplot_figure()
plt.title("LIME Local Explanation")
plt.show()

print("LIME Feature Contributions\n")

for feature, weight in lime_exp.as_list():
    print(f"{feature}: {weight:.4f}")

# Find the first anomaly in the test set
anomaly_index = y_test[y_test == 1].index[0]

lime_exp = lime_explainer.explain_instance(
    X_test.loc[anomaly_index].values,
    xgb.predict_proba,
    num_features=10
)

lime_exp.as_pyplot_figure()
plt.title("LIME Explanation for an Anomaly Prediction")
plt.show()